### ISSUE TITLE
RTSP LIVEVIEW

### ISSUE THREAD

**Issue by ea-juinius** [Th3NiKo/Video-heatmap#1]
Hi, can you tell me how to do this in an rtsp stream for the camera ?

**Comment by Th3NiKo** [comment]
Hey, unfortunately I have never used rtsp stream.
You would need for sure replace this line in _vision_heatmap.py_ 
`capture = cv2.VideoCapture(args.video_file)
`

Some materials i found:
https://stackoverflow.com/questions/40875846/capturing-rtsp-camera-using-opencv-python
https://stackoverflow.com/questions/20891936/rtsp-stream-and-opencv-python

**Comment by ea-juinius** [comment]
Спасибо!
